import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowUpRight, Check, Layers3, Star, Users } from "lucide-react";
import { Header } from "@/components/Header";
import { MapArt } from "@/components/MapArt";
import { basemaps } from "@/lib/data";

export function generateStaticParams(){return basemaps.map(m=>({slug:m.slug}))}
export default async function Detail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const m=basemaps.find(x=>x.slug===slug);if(!m)notFound();return <main className="detail"><Header compact/><div className="detail-shell"><Link href="/#explore" className="back"><ArrowLeft size={16}/> Back to atlas</Link><section className="detail-hero"><div><span className="provider">{m.provider}</span><h1>{m.name}</h1><p>{m.longDescription}</p><div className="detail-actions"><a className="primary" href={m.url} target="_blank" rel="noreferrer">Visit provider <ArrowUpRight size={17}/></a><span className={`price ${m.pricing.toLowerCase()}`}>{m.pricing}</span></div></div><div className="detail-map"><MapArt color={m.color} accent={m.accent}/></div></section><div className="stat-strip"><span><Star size={18}/><b>{m.rating}</b><small>Community rating</small></span><span><Users size={18}/><b>{m.users}</b><small>Estimated users</small></span><span><Layers3 size={18}/><b>{m.formats.length}</b><small>Delivery formats</small></span></div><section className="detail-grid"><article><span className="eyebrow">WORKS WITH</span><h2>GIS compatibility</h2><ul>{m.gis.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></article><article><span className="eyebrow">DELIVERY</span><h2>Available formats</h2><ul>{m.formats.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></article><article><span className="eyebrow">BEST FOR</span><h2>Perfect use cases</h2><ul>{m.bestFor.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></article></section><div className="notice">Plan names, pricing, attribution requirements, and usage limits can change. Review the provider’s current terms before publishing.</div></div></main>}
