export type Basemap = {
  slug: string; name: string; provider: string; description: string; longDescription: string;
  pricing: "Free" | "Freemium" | "Paid"; category: string; color: string; accent: string;
  rating: number; users: string; gis: string[]; formats: string[]; bestFor: string[];
  url: string; featured?: boolean;
};

export const basemaps: Basemap[] = [
  { slug:"mapbox-streets", name:"Mapbox Streets", provider:"Mapbox", description:"A polished, global street map built for modern applications.", longDescription:"A highly customizable vector basemap with rich global road, place, transit, and land-use data. Its strong design system and developer tooling make it a dependable starting point for production web and mobile maps.", pricing:"Freemium", category:"Streets", color:"#d9ded6", accent:"#284b39", rating:4.9, users:"2.4M", gis:["Mapbox GL JS","QGIS","ArcGIS Pro","Leaflet"], formats:["Vector tiles","Raster tiles","Static images"], bestFor:["Navigation","Consumer apps","Data overlays"], url:"https://www.mapbox.com/maps/streets", featured:true },
  { slug:"esri-world-imagery", name:"World Imagery", provider:"Esri", description:"High-resolution satellite and aerial imagery from around the globe.", longDescription:"A detailed global imagery layer assembled from satellite and aerial sources. It is especially useful as geographic context for field mapping, environmental monitoring, land-use analysis, and visual verification.", pricing:"Freemium", category:"Satellite", color:"#243d32", accent:"#d8b46d", rating:4.9, users:"3.1M", gis:["ArcGIS Pro","QGIS","Leaflet","OpenLayers"], formats:["Raster tiles","Map service"], bestFor:["Remote sensing","Field work","Land cover"], url:"https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9", featured:true },
  { slug:"openstreetmap", name:"OpenStreetMap", provider:"OpenStreetMap contributors", description:"The collaborative, open map of the world.", longDescription:"A community-built global geographic database covering roads, paths, amenities, buildings, addresses, and much more. Open data and an enormous ecosystem make it the universal foundation for countless mapping projects.", pricing:"Free", category:"Community", color:"#d6e3cf", accent:"#5a7c3b", rating:4.8, users:"5M+", gis:["QGIS","ArcGIS Pro","Leaflet","OpenLayers"], formats:["Raster tiles","Vector data","PBF"], bestFor:["Open data","Research","Prototyping"], url:"https://www.openstreetmap.org", featured:true },
  { slug:"carto-positron", name:"CARTO Positron", provider:"CARTO", description:"A clean, light canvas designed to let your data lead.", longDescription:"A minimal, neutral basemap with careful hierarchy and restrained labels. Positron is ideal for dashboards, thematic maps, and dense analytical overlays where the basemap should provide context without competing for attention.", pricing:"Free", category:"Light", color:"#e9e6df", accent:"#6a6f76", rating:4.7, users:"890K", gis:["QGIS","Leaflet","MapLibre","CARTO"], formats:["Raster tiles","Vector tiles"], bestFor:["Dashboards","Thematic maps","Print"], url:"https://carto.com/basemaps", featured:true },
  { slug:"stadia-alidade-smooth-dark", name:"Alidade Smooth Dark", provider:"Stadia Maps", description:"A sophisticated dark map for luminous data overlays.", longDescription:"A refined dark canvas that keeps geographic features legible while allowing bright thematic data to command attention. Its subdued palette is well suited to monitoring tools and night-mode interfaces.", pricing:"Freemium", category:"Dark", color:"#151c1b", accent:"#9dd0bd", rating:4.7, users:"410K", gis:["QGIS","Leaflet","MapLibre","OpenLayers"], formats:["Raster tiles","Vector tiles"], bestFor:["Dark UI","Live monitoring","Data viz"], url:"https://stadiamaps.com/stamen/", featured:true },
  { slug:"stamen-toner", name:"Toner", provider:"Stamen", description:"A bold monochrome map with dramatic graphic contrast.", longDescription:"An iconic black-and-white cartographic style with sharp roads, boundaries, labels, and urban texture. It excels in editorial graphics, posters, and maps that need a distinctive visual voice.", pricing:"Freemium", category:"Editorial", color:"#eeeae0", accent:"#171717", rating:4.6, users:"680K", gis:["QGIS","Leaflet","MapLibre"], formats:["Raster tiles"], bestFor:["Editorial","Print","Art maps"], url:"https://stamen.com/work/maps-stamen-com/" },
  { slug:"jawg-terrain", name:"Jawg Terrain", provider:"Jawg Maps", description:"A vivid terrain map for outdoor and topographic stories.", longDescription:"A terrain-focused style that balances relief, trails, land cover, water, and place labels. It provides an inviting visual base for hiking, cycling, tourism, and environmental applications.", pricing:"Freemium", category:"Terrain", color:"#b8c89f", accent:"#395d43", rating:4.6, users:"220K", gis:["QGIS","Leaflet","MapLibre","OpenLayers"], formats:["Raster tiles","Vector tiles"], bestFor:["Outdoors","Tourism","Topography"], url:"https://www.jawg.io/en/maps" },
  { slug:"google-maps", name:"Google Maps", provider:"Google", description:"Familiar global mapping with extensive places and road context.", longDescription:"A widely recognized basemap and platform with comprehensive roads, businesses, landmarks, traffic, and imagery. It is strongest when familiarity, places, routing, and a complete consumer mapping ecosystem matter.", pricing:"Paid", category:"Streets", color:"#d8e4ef", accent:"#3975d1", rating:4.8, users:"10M+", gis:["Google Maps JS API","Android","iOS"], formats:["Web API","Mobile SDK","Static images"], bestFor:["Places","Routing","Consumer apps"], url:"https://mapsplatform.google.com/maps/" },
];

export const categories = ["All maps", "Streets", "Satellite", "Terrain", "Light", "Dark", "Community", "Editorial"];
